program -> stats | EPSILON
stats -> stat stats1 | EPSILON
stats1 -> 'token_salto_linea' stats | EPSILON
stat -> simple_stat | 'token_salto_linea'
simple_stat -> log | leer | importar | expr | atom
log -> 'log' '(' expr ')'
leer -> 'leer' '(' variable ')'
importar -> 'importar' 'id' K | 'desde' 'id' 'importar' 'id'
variable -> 'id' K J
array -> 'OKEY' G 'CKEY'
objeto -> '{' L '}'
Keyvalue -> 'id' ':' expr
K -> '.' 'id' K | EPSILON
L -> Keyvalue M | EPSILON
M -> ',' Keyvalue M | EPSILON
G -> expr H | EPSILON
H -> ',' expr H | EPSILON
J -> '(' G ')' | array | EPSILON
expr -> '!' expr | '-' expr | '(' expr ')' | atom op
op -> N expr | EPSILON
N -> '^' | '*' | '/' | '%' | '+' | '-' | '=' | '<=' | '>=' | '<' | '>' | '==' | '!=' | '&&' | 'OR'
atom -> 'token_integer' | 'token_float' | 'true' | 'false' | 'token_string' | array | variable | 'nil' | objeto
