program -> stats | EPSILON
stats -> B stat stats1 | EPSILON
stats1 -> A stats | EPSILON
stat -> simple_stat | compound_stat

simple_stat -> log | leer | importar | expr
compound_stat -> funcion

log -> 'log' '(' expr ')'
leer -> 'leer' '(' variable ')'
importar -> 'importar' 'id' K | 'desde' 'id' 'importar' 'id'

funcion -> 'funcion' 'id' '(' parametros ')' stat_block 'end' 'funcion'
parametros -> 'id' parametro | EPSILON
parametro -> ',' 'id' parametro | EPSILON

A -> 'token_salto_linea' B
B -> 'token_salto_linea' B | EPSILON
stat_block -> '{' stats '}' | A stat A
variable -> 'id' K J
array -> 'OKEY' G 'CKEY'
objeto -> '{' L '}'
Keyvalue -> 'id' ':' expr
K -> '.' 'id' K | EPSILON
L -> Keyvalue M | EPSILON
M -> ',' Keyvalue M | EPSILON
G -> expr H | EPSILON
H -> ',' expr H | EPSILON
J -> '(' G ')' | array | EPSILON
expr -> '!' expr | '-' expr | '(' expr ')' | atom op
op -> N expr | EPSILON
N -> '^' | '*' | '/' | '%' | '+' | '-' | '=' | '<=' | '>=' | '<' | '>' | '==' | '!=' | '&&' | 'OR'
atom -> 'token_integer' | 'token_float' | 'true' | 'false' | 'token_string' | array | variable | 'nil' | objeto
